server:
  port: ${AUTH_SERVICE_PORT:8080}
  servlet:
    session:
      cookie:
        name: ${AUTH_SESSION_COOKIE_NAME:WISHLISTSESSION}

spring:
  datasource:
    url: ${AUTH_DB_URL}
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${AUTH_JPA_DDL_AUTO:update}
    show-sql: ${AUTH_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${AUTH_REDIS_HOST:redis}
      port: ${AUTH_REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    properties:
      spring.json.add.type.headers: false
