
services:
  frontend:
    container_name: wishlist-frontend
    build: ./wishlist-app-frontend
    environment:
      VITE_API_AUTH_URL: ${AUTH_URL}
    depends_on:
      auth-service:
        condition: service_started
    restart: unless-stopped
    ports:
      - "5173:5173"


  auth-service:
    build: ./Auth-Service
    container_name: auth-service

    depends_on:
      auth-db:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started

    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_ALLOWED_ORIGINS: ${SPRING_ALLOWED_ORIGINS}

      AUTH_SERVICE_PORT: 8080

      AUTH_DB_URL: ${AUTH_DB_DOCKER_URL}
      AUTH_DB_USER: ${AUTH_DB_USER}
      AUTH_DB_PASSWORD: ${AUTH_DB_PASSWORD}
      AUTH_JPA_DDL_AUTO: ${AUTH_JPA_DDL_AUTO}
      AUTH_JPA_SHOW_SQL: ${AUTH_JPA_SHOW_SQL}

      AUTH_REDIS_HOST: ${AUTH_REDIS_HOST}
      AUTH_REDIS_PORT: ${AUTH_REDIS_PORT}

      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS_DOCKER}

      AUTH_SESSION_COOKIE_NAME: ${AUTH_SESSION_COOKIE_NAME}

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_FIRST_NAME: ${ADMIN_FIRST_NAME}
      ADMIN_LAST_NAME: ${ADMIN_LAST_NAME}

  auth-db:
    image: postgres:16
    restart: unless-stopped
    container_name: auth-db
    environment:
      POSTGRES_DB: ${AUTH_DB}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
  redis:
    image: redis:7
    container_name: wishlist-redis
    ports:
      - "6379:6379"
  kafka:
    image: apache/kafka:latest
    container_name: wishlist-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: "true"
      CLUSTER_ID: "123-H1wort-43-1XLr"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LOG_DIRS: "/tmp/kraft-logs"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    volumes:
      - kafka_kraft:/var/lib/kafka/data

volumes:
  auth-db-data:
  kafka_kraft:
