name: Auth-Service CI

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "Auth-Service/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: Auth-Service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Set up Gradle (cache)
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests (with Testcontainers)
        env:
          SPRING_PROFILES_ACTIVE: test
        run: ./gradlew clean test

      - name: Run Spotless
        run: ./gradlew spotlessCheck
      - name: Run Checkstyle
        run: ./gradlew checkstyleMain
  
        # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
        # the publishing section of your build.gradle
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

